# Generated by Django 5.2.10 on 2026-01-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
